'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Location

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateLabel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label123 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Branch_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Branch_List As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Load_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Load_Location As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Location_head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Location_head As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc1_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc1_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc1_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc1_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc2_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc2_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc2_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc2_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc3_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc3_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc3_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc3_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc4_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc4_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc4_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc4_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc5_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc5_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc5_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc5_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc6_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc6_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc6_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc6_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc7_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc7_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc7_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc7_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc8_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc8_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc8_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc8_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc9_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc9_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc9_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc9_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc10_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc10_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc10_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc10_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel11 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc11_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc11_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc11_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc11_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel12 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc12_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc12_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc12_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc12_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel13 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel14 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc13_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc13_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc13_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc13_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel15 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc14_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc14_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc14_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc14_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel16 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc15_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc15_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc15_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc15_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel17 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc16_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc16_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc16_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc16_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc17_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc17_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc17_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc17_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel19 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc18_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc18_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc18_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc18_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel20 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc19_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc19_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc19_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc19_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel21 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc20_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc20_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc20_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc20_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel22 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc21_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc21_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc21_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc21_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc22_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc22_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc22_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc22_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel24 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc23_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc23_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc23_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc23_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel25 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc24_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc24_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc24_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc24_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel26 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel27 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc25_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc25_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc25_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc25_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel28 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc26_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc26_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc26_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc26_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel29 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc27_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc27_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc27_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc27_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel30 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc28_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc28_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc28_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc28_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel31 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc29_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc29_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc29_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc29_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel32 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc30_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc30_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc30_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc30_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel33 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc31_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc31_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc31_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc31_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel34 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc32_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc32_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc32_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc32_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc32 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel35 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc33_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc33_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc33_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc33_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel36 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc34_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc34_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc34_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc34_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc34 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel37 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc35_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc35_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc35_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc35_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc35 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel38 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc36_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc36_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc36_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc36_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc36 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel39 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel40 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc37_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc37_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc37_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc37_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc37 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel41 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc38_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc38_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc38_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc38_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc38 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel42 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc39_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc39_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc39_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc39_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc39 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel43 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc40_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc40_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc40_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc40_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc40 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel44 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc41_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc41_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc41_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc41_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc41 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel45 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc42_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc42_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc42_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc42_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc42 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel46 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc43_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc43_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc43_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc43_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc43 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel47 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc44_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc44_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc44_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc44_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc44 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel48 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc45_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc45_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc45_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc45_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc45 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel49 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc46_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc46_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc46_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc46_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc46 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel50 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc47_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc47_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc47_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc47_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc47 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel51 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''loc48_Tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc48_Tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc48_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc48_P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loc48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loc48 As Global.System.Web.UI.WebControls.Label
End Class
